#!/bin/bash

#Wählt im Rathaus die entsprechende Rohstoffkategorie an.
#(von links nach recht: 1=einfach, 2=verbessert, ..., 6=sammlungen)

[[ $# -eq 0 ]] && exit 0

if [[ $1 =~ ^[1-6]$  ]] ; then
	left $((1259+$1*86)) 975 0.3
else
	echo "s_select_rathaus_rohstoff: Argument should be 1 to 6."
fi
