#!/bin/bash

sleep 5

x=$(gml)
for i in {1..20} ; do
  if [[ $(gml) != $x ]] ; then
    notify-send "user present"
    exit 0
  fi
  sleep 1
done

xdotool mousemove 30 115
sleep 1
xdotool click 1
sleep 5
for i in s space h space p o w Return ; do
	xdotool key $i
	sleep 0.1
done
