#!/bin/bash
# Schreibt das erste Argument als simulierte Tastendrücke

#for i in $(seq 1 ${#1}) ; do xdotool key ${1:$[$i-1]:1} ; done
for i in $(echo $1 | sed -r 's/(.)/\1 /g;s/\$/dollar/g;s/ü/udiaeresis/g;s/\^/asciicircum/g') ; do
	xdotool key $i
done
